[theme]
primaryColor = "#DC0D15"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1A1A1A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
runOnSave = true

